% PDF: logistics_pn_pdf.m
%
% %%%%%%%   Logistikk avdeling
% To lagerplasser (Yard1, Yard2) med ulik avstand til verkstedet
% Lastebil kjører tom til en yard, laster med truck, kjører tilbake
% Lossing med truck på verkstedet -> Output buffer (rør levert)
% Avstand modelleres som firing time på kjøre-transitionene (settes i MSF)

function [pns] = logistics_pn_pdf()

pns.PN_name = 'Logistics Petri Net model';
pns.set_of_Ps = {'pYard1', 'pYard2', 'pTruckAvailable', ...
                 'pTruckAtYard1', 'pTruckAtYard2', 'pLoaded1', 'pLoaded2', ...
                 'pForkliftYard1', 'pForkliftYard2', 'pForkliftWorkshop', ...
                 'pAtDestination', 'pLogOutput'};
pns.set_of_Ts = {'tDriveToYard1', 'tDriveToYard2', 'tLoad1', 'tLoad2', ...
                 'tDriveFromYard1', 'tDriveFromYard2', 'tUnload'};
pns.set_of_As = { ...
  'pTruckAvailable', 'tDriveToYard1',   1, 'pYard1', 'tDriveToYard1', 1 ... % Drive empty to yard 1 (only if pipes there)
  'tDriveToYard1',   'pTruckAtYard1',   1 ...
  'pTruckAvailable', 'tDriveToYard2',   1, 'pYard2', 'tDriveToYard2', 1 ... % Drive empty to yard 2
  'tDriveToYard2',   'pTruckAtYard2',   1 ...
  'pTruckAtYard1',   'tLoad1', 1, 'pForkliftYard1', 'tLoad1', 1 ...       % Load at yard 1
  'tLoad1', 'pLoaded1', 1, 'tLoad1', 'pForkliftYard1', 1 ...
  'pTruckAtYard2',   'tLoad2', 1, 'pForkliftYard2', 'tLoad2', 1 ...       % Load at yard 2
  'tLoad2', 'pLoaded2', 1, 'tLoad2', 'pForkliftYard2', 1 ...
  'pLoaded1', 'tDriveFromYard1', 1, 'tDriveFromYard1', 'pAtDestination', 1 ... % Drive back from yard 1
  'pLoaded2', 'tDriveFromYard2', 1, 'tDriveFromYard2', 'pAtDestination', 1 ... % Drive back from yard 2
  'pAtDestination', 'tUnload', 1, 'pForkliftWorkshop', 'tUnload', 1 ...   % Unload at workshop
  'tUnload', 'pLogOutput', 1, 'tUnload', 'pForkliftWorkshop', 1 ...
  'tUnload', 'pTruckAvailable', 1 ...
 };
